proxies:
- name: ğŸš©CF | ğŸŸ¢ | vmess | @ShadowProxy66 | 9
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: 8f9106d9-1d72-5757-bc92-6e832933c810
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: Nl2.vmess.site.
  network: ws
  ws-opts:
    path: /vmess
    headers:
      Host: Nl2.vmess.site.
  udp: true
- name: ğŸ‡¹ğŸ‡·TR | ğŸŸ¢ | vmess | @DailyV2RY | 279
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: 7c7af2de-bb97-429f-ac3c-8ef849717491
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: irtr1.ngiftcard.com
  network: ws
  ws-opts:
    path: /34L4qODA1XwJYopk6e398A
    headers:
      Host: irtr1.ngiftcard.com
  udp: true
- name: ğŸ‡¸ğŸ‡ªSE | ğŸŸ¢ | vmess | @proxystore11 | 5
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: 8639e52b-a0ce-5d68-b465-b594881feb78
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: De1.vmess.site.
  network: ws
  ws-opts:
    path: /vmess
    headers:
      Host: De1.vmess.site.
  udp: true
- name: ğŸ‡¨ğŸ‡³CN | ğŸŸ¢ | vmess | @yaney_01 | 4
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: 46cfcfe1-e450-459d-a3ab-9406011ab3eb
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: tms.dingtalk.com
  network: ws
  ws-opts:
    path: /
    headers:
      Host: tms.dingtalk.com
  udp: true
- name: â”XX | ğŸŸ¢ | vmess | @Hope_Net | 0
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: 9b641bd5-6b80-359e-a23a-eb7b6f21fc1a
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: '%7B%22Host%22:%22data.video.qiyi.com%22%7D'
  network: ws
  ws-opts:
    path: /qatjpji
    headers:
      Host: '%7B%22Host%22:%22data.video.qiyi.com%22%7D'
  udp: true
- name: ğŸš©CF | ğŸŸ¢ | vmess | @v2Line | 0
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: 6965a407-7549-436e-8064-22e3d3d2e7cd
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: 58892877706648357761980405045364.chrsjfklsdjfkljoierfdjklfjlkefeojsdlkfjeoifjsdlkfjweoifjlsdchrs.cyou
  network: ws
  ws-opts:
    path: /V2LINE-TELEGRAM-CHANNEL-VMESS-WS
    headers:
      Host: 58892877706648357761980405045364.chrsjfklsdjfkljoierfdjklfjlkefeojsdlkfjeoifjsdlkfjweoifjlsdchrs.cyou
  udp: true
- name: ğŸš©CF | ğŸŸ¢ | vmess | @v2Line | 1
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: 3e5cda0a-6122-4f54-9e3c-3f49e7a526f9
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: nlch.blueberrynetwork.store
  network: ws
  ws-opts:
    path: /
    headers:
      Host: nlch.blueberrynetwork.store
  udp: true
- name: 'ğŸ†” @v2ray_configs_pool '
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: cb4fca5f-edf8-415b-aa8f-ac52f415296a
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: deefull.tradex2080.com
  network: ws
  ws-opts:
    path: /0fpZFB6IbpNptGAxAtI0QM
    headers:
      Host: deefull.tradex2080.com
  udp: true
- name: 'ğŸ†” @v2ray_configs_pool '
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: 6965a407-7549-436e-8064-22e3d3d2e7cd
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: 58892877706648357761980405045364.chrsjfklsdjfkljoierfdjklfjlkefeojsdlkfjeoifjsdlkfjweoifjlsdchrs.cyou
  network: ws
  ws-opts:
    path: /V2LINE-TELEGRAM-CHANNEL-VMESS-WS
    headers:
      Host: 58892877706648357761980405045364.chrsjfklsdjfkljoierfdjklfjlkefeojsdlkfjeoifjsdlkfjweoifjlsdchrs.cyou
  udp: true
- name: 'ğŸ†” @v2ray_configs_pool '
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: 22a13aa2-4854-44cb-e090-ec71ab84b1ff
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: wap.hostmjj.com
  network: ws
  ws-opts:
    path: /
    headers:
      Host: wap.hostmjj.com
  udp: true
- name: 'ğŸ†” @v2ray_configs_pool '
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: f533e37c-9da5-4955-a218-a7886e5719b6
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: nl88.tradex2080.com
  network: ws
  ws-opts:
    path: /NkXnI0l6LGkotMyATWmx5f6MblN
    headers:
      Host: nl88.tradex2080.com
  udp: true
- name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡(æ²¹ç®¡:ç ´è§£èµ„æºå›2.0)
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: e982184f-c6e0-4ba4-91cc-71eb6c702588
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: frontier-i18n.tiktokv.com
  network: ws
  ws-opts:
    path: /nkpvpn.site
    headers:
      Host: frontier-i18n.tiktokv.com
  udp: true
- name: ğŸ‡ªğŸ‡º æ¬§æ´²(æ²¹ç®¡:ç ´è§£èµ„æºå›2.0)
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: 29d057f9-1600-4a18-b595-62a14073a230
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: 144.24.92.192
  network: tcp
  ws-opts:
    path: /
    headers:
      Host: 144.24.92.192
  udp: true
- name: ğŸ‡ªğŸ‡º æ¬§æ´²(æ²¹ç®¡:ç ´è§£èµ„æºå›2.0)
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: cb81e6ab-1d83-4ac1-f0ad-ae5c2a7c29ef
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: 8.214.33.158
  network: ws
  ws-opts:
    path: /
    headers:
      Host: 8.214.33.158
  udp: true
- name: ğŸ‡ªğŸ‡º æ¬§æ´²(æ²¹ç®¡:ç ´è§£èµ„æºå›2.0)
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: cb81e6ab-1d83-4ac1-f0ad-ae5c2a7c29ef
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: 8.214.33.158
  network: ws
  ws-opts:
    path: /
    headers:
      Host: 8.214.33.158
  udp: true
- name: ''
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: 533724ad-58ef-4147-88dc-9da523c15fc4
  alterId: 64
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: 159.223.94.156
  network: ws
  ws-opts:
    path: /anti13.zingfast.vn
    headers:
      Host: 159.223.94.156
  udp: true
- name: ğŸ‡¯ğŸ‡µ 10,11|æ—¥æœ¬4|@ripaojiedian
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: 9a403efc-18d7-4a78-8532-fb15541ef836
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: 6Sn8mFtTjp3.yofnhkfc.xyz
  network: ws
  ws-opts:
    path: /video/X37qXHip
    headers:
      Host: 6Sn8mFtTjp3.yofnhkfc.xyz
  udp: true
- name: ğŸ”’ VM-WS-NA ğŸ‡ºğŸ‡¸ US-155.138.242.207:80
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: 81f40c2c-e3e8-4e0a-cb51-33db25e20b97
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: 155.138.242.207
  network: ws
  ws-opts:
    path: /
    headers:
      Host: 155.138.242.207
  udp: true
- name: æ›´æ–°äº 08-13 01:45 by https://github.com/ts-sf/fly
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: 602736e4-a2e8-4eb3-9fc9-7c7082925365
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: 127.1.1.127
  network: tcp
  ws-opts:
    path: ''
    headers:
      Host: 127.1.1.127
  udp: true
- name: æœªçŸ¥5
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: 8639e52b-a0ce-5d68-b465-b594881feb78
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: De1.vmess.site.
  network: ws
  ws-opts:
    path: /vmess
    headers:
      Host: De1.vmess.site.
  udp: true
- name: æœªçŸ¥51
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: 3e5cda0a-6122-4f54-9e3c-3f49e7a526f9
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: nlch.blueberrynetwork.store
  network: ws
  ws-opts:
    path: /
    headers:
      Host: nlch.blueberrynetwork.store
  udp: true
- name: æœªçŸ¥108 356.6KB/s
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: 6965a407-7549-436e-8064-22e3d3d2e7cd
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: 58892877706648357761980405045364.chrsjfklsdjfkljoierfdjklfjlkefeojsdlkfjeoifjsdlkfjweoifjlsdchrs.cyou
  network: ws
  ws-opts:
    path: /V2LINE-TELEGRAM-CHANNEL-VMESS-WS
    headers:
      Host: 58892877706648357761980405045364.chrsjfklsdjfkljoierfdjklfjlkefeojsdlkfjeoifjsdlkfjweoifjlsdchrs.cyou
  udp: true
- name: 10,11|æ—¥æœ¬4|@ripaojiedian
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: 9a403efc-18d7-4a78-8532-fb15541ef836
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: 6Sn8mFtTjp3.yofnhkfc.xyz
  network: ws
  ws-opts:
    path: /video/X37qXHip
    headers:
      Host: 6Sn8mFtTjp3.yofnhkfc.xyz
  udp: true
- name: ğŸRELAY-104.16.67.38-1280
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: 2a8a10fb-9ca3-367e-a234-cf09f841be4f
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: us3e-mmnnfr9dop0.v2freevpn.com
  network: ws
  ws-opts:
    path: /v118-fccxmxm35
    headers:
      Host: us3e-mmnnfr9dop0.v2freevpn.com
  udp: true
- name: ğŸ†”dailyv2ry ğŸ”“ VM-WS-N/A ğŸ‡ºğŸ‡¸ US 2ms
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: f533e37c-9da5-4955-a218-a7886e5719b6
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: nl88.tradex2080.com
  network: ws
  ws-opts:
    path: /NkXnI0l6LGkotMyATWmx5f6MblN
    headers:
      Host: nl88.tradex2080.com
  udp: true
- name: ğŸ†”v2line ğŸ”“ VM-WS-N/A ğŸ‡ºğŸ‡¸ US 2ms
  server: 104.26.6.171
  port: 80
  type: vmess
  uuid: 6965a407-7549-436e-8064-22e3d3d2e7cd
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: 58892877706648357761980405045364.chrsjfklsdjfkljoierfdjklfjlkefeojsdlkfjeoifjsdlkfjweoifjlsdchrs.cyou
  network: ws
  ws-opts:
    path: /V2LINE-TELEGRAM-CHANNEL-VMESS-WS
    headers:
      Host: 58892877706648357761980405045364.chrsjfklsdjfkljoierfdjklfjlkefeojsdlkfjeoifjsdlkfjweoifjlsdchrs.cyou
  udp: true
