proxies:
- name: ğŸš©CF | ğŸŸ¢ | vmess | @V2rayCollectorDonate | 4
  server: 172.67.71.160
  port: 443
  type: vmess
  uuid: 05641cf5-58d2-4ba4-a9f1-b3cda0b1fb1d
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: obdii.cfd
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: obdii.cfd
  udp: true
- name: ğŸš©CF | ğŸŸ¢ | vmess | @ShadowProxy66 | 13
  server: 172.67.183.220
  port: 443
  type: vmess
  uuid: 950db6aa-4926-4616-816e-ec0312dcb87b
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: jahfkjha.cfd
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: jahfkjha.cfd
  udp: true
- name: ğŸš©CF | ğŸŸ¢ | vmess | @ShadowProxy66 | 14
  server: 172.67.138.140
  port: 443
  type: vmess
  uuid: 441da342-ce90-441e-bff9-d2ceb55e68ca
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ivideos.sbs
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: ivideos.sbs
  udp: true
- name: ğŸš©CF | ğŸŸ¢ | vmess | @ShadowProxy66 | 16
  server: 104.21.9.236
  port: 443
  type: vmess
  uuid: 62aa5f80-0328-4004-a375-7f5a59df4022
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: hms19.best-tizi.top
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: hms19.best-tizi.top
  udp: true
- name: ğŸš©CF | ğŸŸ¢ | vmess | @ShadowProxy66 | 17
  server: 172.67.146.10
  port: 443
  type: vmess
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: sareikela.com
  network: ws
  ws-opts:
    path: /linkvws
    headers:
      Host: sareikela.com
  udp: true
- name: ğŸš©CF | ğŸŸ¢ | vmess | @v2ray1_ng | 9
  server: 104.21.94.64
  port: 443
  type: vmess
  uuid: 39cec18f-a439-427c-9a4e-aeb6fcdf6f53
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: linja05.hwcar.sbs
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: linja05.hwcar.sbs
  udp: true
- name: ğŸš©CF | ğŸŸ¢ | vmess | @proxystore11 | 7
  server: 172.67.71.160
  port: 443
  type: vmess
  uuid: 05641cf5-58d2-4ba4-a9f1-b3cda0b1fb1d
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: obdii.cfd
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: obdii.cfd
  udp: true
- name: ğŸš©CF | ğŸŸ¢ | vmess | @yaney_01 | 5
  server: 104.26.8.210
  port: 443
  type: vmess
  uuid: 206259fd-09af-46ee-ec6d-5ac8a8291d6d
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: uyhgiuyfewdrgf-to12345.xiaohhh.xyz
  network: ws
  ws-opts:
    path: /66
    headers:
      Host: uyhgiuyfewdrgf-to12345.xiaohhh.xyz
  udp: true
- name: ğŸš©CF | ğŸŸ¢ | vmess | @Hope_Net | 2
  server: 172.67.220.83
  port: 443
  type: vmess
  uuid: 39cec18f-a439-427c-9a4e-aeb6fcdf6f53
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: linja05.hwcar.sbs
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: linja05.hwcar.sbs
  udp: true
- name: ğŸ”’ VM-WS-TLS ğŸ‡ºğŸ‡¸ US-151.101.2.219:443
  server: 151.101.2.219
  port: 443
  type: vmess
  uuid: e3be9709-88bf-42b2-a431-573c91c13e28
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: Dbdjhiw72ebsu272hs519j.com
  network: ws
  ws-opts:
    path: ws/?ed=2048
    headers:
      Host: Dbdjhiw72ebsu272hs519j.com
  udp: true
- name: 'ğŸ†” @v2ray_configs_pool '
  server: 172.67.71.160
  port: 443
  type: vmess
  uuid: 05641cf5-58d2-4ba4-a9f1-b3cda0b1fb1d
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: obdii.cfd
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: obdii.cfd
  udp: true
- name: 'ğŸ†” @v2ray_configs_pool '
  server: 172.67.220.83
  port: 443
  type: vmess
  uuid: 39cec18f-a439-427c-9a4e-aeb6fcdf6f53
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: linja05.hwcar.sbs
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: linja05.hwcar.sbs
  udp: true
- name: 'ğŸ†” @v2ray_configs_pool '
  server: 188.114.97.210
  port: 443
  type: vmess
  uuid: edbb1059-1633-4271-b66e-ed4fba47a1bf
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: linde06.indiavideo.sbs
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: linde06.indiavideo.sbs
  udp: true
- name: 'ğŸ†” @v2ray_configs_pool '
  server: 104.21.9.236
  port: 443
  type: vmess
  uuid: 62aa5f80-0328-4004-a375-7f5a59df4022
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: hms19.best-tizi.top
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: hms19.best-tizi.top
  udp: true
- name: 'ğŸ†” @v2ray_configs_pool '
  server: 172.67.146.10
  port: 443
  type: vmess
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: sareikela.com
  network: ws
  ws-opts:
    path: /linkvws
    headers:
      Host: sareikela.com
  udp: true
- name: 'ğŸ†” @v2ray_configs_pool '
  server: 172.67.156.22
  port: 443
  type: vmess
  uuid: f584de15-2034-4170-a723-f48c2bae5e0f
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: nezuko.raidenshogun.cloudns.org
  network: ws
  ws-opts:
    path: /linkws/afrhms16v.bestxray.buzz
    headers:
      Host: nezuko.raidenshogun.cloudns.org
  udp: true
- name: 'ğŸ†” @v2ray_configs_pool '
  server: 172.67.138.140
  port: 443
  type: vmess
  uuid: 441da342-ce90-441e-bff9-d2ceb55e68ca
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ivideos.sbs
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: ivideos.sbs
  udp: true
- name: 'ğŸ†” @v2ray_configs_pool '
  server: 202.78.162.5
  port: 443
  type: vmess
  uuid: 716eded6-2201-4dbd-9d63-1638c9e8e677
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: pendar.onthewifi.com
  network: ws
  ws-opts:
    path: /@forwardv2ray
    headers:
      Host: pendar.onthewifi.com
  udp: true
- name: 'ğŸ†” @v2ray_configs_pool '
  server: gov.uk
  port: 443
  type: vmess
  uuid: 77848824-93b7-4b89-ffd0-e91afff406ce
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: zheshiscp.com
  network: ws
  ws-opts:
    path: /77848824
    headers:
      Host: zheshiscp.com
  udp: true
- name: 'ğŸ†” @v2ray_configs_pool '
  server: 202.78.162.5
  port: 443
  type: vmess
  uuid: 2ff97c6d-8557-42a4-b43f-19c77c5959ea
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: irsoft.sytes.net
  network: ws
  ws-opts:
    path: /@forwardv2ray
    headers:
      Host: irsoft.sytes.net
  udp: true
- name: 'ğŸ†” @v2ray_configs_pool '
  server: 202.78.162.5
  port: 443
  type: vmess
  uuid: 118287d2-e968-42e1-80d0-12fa2f5d38d6
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: sahand.serveminecraft.net
  network: ws
  ws-opts:
    path: /@forwardv2ray
    headers:
      Host: sahand.serveminecraft.net
  udp: true
- name: ğŸRELAY-104.21.24.170-0541
  server: denc36.xtooltech.cfd
  port: 443
  type: vmess
  uuid: b321fd5d-e6ec-4293-a644-164e3885f52e
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: adenc36v.xtooltech.cfd
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: adenc36v.xtooltech.cfd
  udp: true
- name: ğŸ‡¨ğŸ‡¦CA-158.51.121.36-3031
  server: 158.51.121.36
  port: 443
  type: vmess
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: 158.51.121.36
  network: ws
  ws-opts:
    path: /linkvws
    headers:
      Host: 158.51.121.36
  udp: true
- name: ğŸRELAY-104.21.95.165-0569
  server: 104.21.95.165
  port: 443
  type: vmess
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: sareikela.com
  network: ws
  ws-opts:
    path: /linkvws
    headers:
      Host: sareikela.com
  udp: true
- name: ğŸRELAY-104.21.95.165-0519
  server: sareikela.com
  port: 443
  type: vmess
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: sareikela.com
  network: ws
  ws-opts:
    path: /linkvws
    headers:
      Host: sareikela.com
  udp: true
- name: ğŸRELAY-104.21.77.29-0588
  server: beyonddbc.sbs
  port: 443
  type: vmess
  uuid: 8d90c129-4156-4d6c-9115-24df25f26a02
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: beyonddbc.sbs
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: beyonddbc.sbs
  udp: true
- name: ğŸRELAY-172.67.198.19-0474
  server: s.marktred.com
  port: 443
  type: vmess
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: false
  servername: aveiror.com
  network: ws
  ws-opts:
    path: /linkvws
    headers:
      Host: aveiror.com
  udp: true
- name: ğŸRELAY-172.67.174.42-2915
  server: hms082.gwdef.sbs
  port: 443
  type: vmess
  uuid: bc864078-dcf3-4bf4-8dbf-ca9f200b56be
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: gwdef.sbs
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: gwdef.sbs
  udp: true
- name: ğŸRELAY-104.21.82.17-0535
  server: 104.21.82.17
  port: 443
  type: vmess
  uuid: bc864078-dcf3-4bf4-8dbf-ca9f200b56be
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: gwdef.sbs
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: gwdef.sbs
  udp: true
- name: ğŸ‡«ğŸ‡·FR-146.19.168.161-0539
  server: az05.beyondy.cfd
  port: 443
  type: vmess
  uuid: 3f638f34-8dba-4186-bc43-2716a7ddd4be
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: az05.beyondy.cfd
  network: ws
  ws-opts:
    path: /link
    headers:
      Host: az05.beyondy.cfd
  udp: true
- name: ğŸRELAY-188.114.99.205-0516
  server: 188.114.99.205
  port: 443
  type: vmess
  uuid: edbb1059-1633-4271-b66e-ed4fba47a1bf
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: false
  servername: linde06.indiavideo.sbs
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: linde06.indiavideo.sbs
  udp: true
- name: ğŸ‡­ğŸ‡°HK-103.212.98.234-1209
  server: 103.212.98.234
  port: 443
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: true
  skip-cert-verify: false
  servername: www.59795160.xyz
  network: ws
  ws-opts:
    path: /path/011410073331
    headers:
      Host: www.59795160.xyz
  udp: true
- name: ğŸRELAY-104.21.24.170-0309
  server: 104.21.24.170
  port: 443
  type: vmess
  uuid: b321fd5d-e6ec-4293-a644-164e3885f52e
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: adenc36v.xtooltech.cfd
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: adenc36v.xtooltech.cfd
  udp: true
- name: Ø±Ø§ÛŒÚ¯Ø§Ù† | VMESS | @V2rayCollectorDonate | USğŸ‡ºğŸ‡¸ | 0ï¸âƒ£1ï¸âƒ£
  server: 172.67.71.160
  port: 443
  type: vmess
  uuid: 05641cf5-58d2-4ba4-a9f1-b3cda0b1fb1d
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: obdii.cfd
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: obdii.cfd
  udp: true
- name: Ø±Ø§ÛŒÚ¯Ø§Ù† | VMESS | @ShadowProxy66 | USğŸ‡ºğŸ‡¸ | 0ï¸âƒ£1ï¸âƒ£
  server: 172.67.183.220
  port: 443
  type: vmess
  uuid: 950db6aa-4926-4616-816e-ec0312dcb87b
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: jahfkjha.cfd
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: jahfkjha.cfd
  udp: true
- name: Ø±Ø§ÛŒÚ¯Ø§Ù† | VMESS | @ShadowProxy66 | USğŸ‡ºğŸ‡¸ | 0ï¸âƒ£2ï¸âƒ£
  server: 172.67.138.140
  port: 443
  type: vmess
  uuid: 441da342-ce90-441e-bff9-d2ceb55e68ca
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ivideos.sbs
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: ivideos.sbs
  udp: true
- name: Ø±Ø§ÛŒÚ¯Ø§Ù† | VMESS | @ShadowProxy66 | USğŸ‡ºğŸ‡¸ | 0ï¸âƒ£4ï¸âƒ£
  server: 104.21.9.236
  port: 443
  type: vmess
  uuid: 62aa5f80-0328-4004-a375-7f5a59df4022
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: hms19.best-tizi.top
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: hms19.best-tizi.top
  udp: true
- name: Ø±Ø§ÛŒÚ¯Ø§Ù† | VMESS | @ShadowProxy66 | USğŸ‡ºğŸ‡¸ | 0ï¸âƒ£5ï¸âƒ£
  server: 172.67.146.10
  port: 443
  type: vmess
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: sareikela.com
  network: ws
  ws-opts:
    path: /linkvws
    headers:
      Host: sareikela.com
  udp: true
- name: Ø±Ø§ÛŒÚ¯Ø§Ù† | VMESS | @v2ray1_ng | USğŸ‡ºğŸ‡¸ | 0ï¸âƒ£1ï¸âƒ£
  server: 104.21.94.64
  port: 443
  type: vmess
  uuid: 39cec18f-a439-427c-9a4e-aeb6fcdf6f53
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: linja05.hwcar.sbs
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: linja05.hwcar.sbs
  udp: true
- name: Ø±Ø§ÛŒÚ¯Ø§Ù† | VMESS | @proxystore11 | USğŸ‡ºğŸ‡¸ | 0ï¸âƒ£2ï¸âƒ£
  server: 172.67.71.160
  port: 443
  type: vmess
  uuid: 05641cf5-58d2-4ba4-a9f1-b3cda0b1fb1d
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: obdii.cfd
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: obdii.cfd
  udp: true
- name: Ø±Ø§ÛŒÚ¯Ø§Ù† | VMESS | @Hope_Net | USğŸ‡ºğŸ‡¸ | 0ï¸âƒ£1ï¸âƒ£
  server: 172.67.220.83
  port: 443
  type: vmess
  uuid: 39cec18f-a439-427c-9a4e-aeb6fcdf6f53
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: linja05.hwcar.sbs
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: linja05.hwcar.sbs
  udp: true
