proxies:
- name: ğŸš©CF | ğŸŸ¢ | vmess | @ShadowProxy66 | 9
  server: 172.67.171.48
  port: 80
  type: vmess
  uuid: 8f9106d9-1d72-5757-bc92-6e832933c810
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: Nl2.vmess.site.
  network: ws
  ws-opts:
    path: /vmess
    headers:
      Host: Nl2.vmess.site.
  udp: true
- name: ğŸ‡¹ğŸ‡·TR | ğŸŸ¢ | vmess | @DailyV2RY | 279
  server: irtr1.ngiftcard.com
  port: 80
  type: vmess
  uuid: 7c7af2de-bb97-429f-ac3c-8ef849717491
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: irtr1.ngiftcard.com
  network: ws
  ws-opts:
    path: /34L4qODA1XwJYopk6e398A
    headers:
      Host: irtr1.ngiftcard.com
  udp: true
- name: ğŸ‡¸ğŸ‡ªSE | ğŸŸ¢ | vmess | @proxystore11 | 5
  server: 185.146.173.92
  port: 80
  type: vmess
  uuid: 8639e52b-a0ce-5d68-b465-b594881feb78
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: De1.vmess.site.
  network: ws
  ws-opts:
    path: /vmess
    headers:
      Host: De1.vmess.site.
  udp: true
- name: ğŸ‡¨ğŸ‡³CN | ğŸŸ¢ | vmess | @yaney_01 | 4
  server: ddd47481-0d6f-08b9-7209-b0ddc0c5fa45.oneplus.pub
  port: 80
  type: vmess
  uuid: 46cfcfe1-e450-459d-a3ab-9406011ab3eb
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: tms.dingtalk.com
  network: ws
  ws-opts:
    path: /
    headers:
      Host: tms.dingtalk.com
  udp: true
- name: â”XX | ğŸŸ¢ | vmess | @Hope_Net | 0
  server: jp2.elkcloud.cf
  port: 80
  type: vmess
  uuid: 9b641bd5-6b80-359e-a23a-eb7b6f21fc1a
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: '%7B%22Host%22:%22data.video.qiyi.com%22%7D'
  network: ws
  ws-opts:
    path: /qatjpji
    headers:
      Host: '%7B%22Host%22:%22data.video.qiyi.com%22%7D'
  udp: true
- name: ğŸš©CF | ğŸŸ¢ | vmess | @v2Line | 0
  server: 104.26.15.148
  port: 80
  type: vmess
  uuid: 6965a407-7549-436e-8064-22e3d3d2e7cd
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: 58892877706648357761980405045364.chrsjfklsdjfkljoierfdjklfjlkefeojsdlkfjeoifjsdlkfjweoifjlsdchrs.cyou
  network: ws
  ws-opts:
    path: /V2LINE-TELEGRAM-CHANNEL-VMESS-WS
    headers:
      Host: 58892877706648357761980405045364.chrsjfklsdjfkljoierfdjklfjlkefeojsdlkfjeoifjsdlkfjweoifjlsdchrs.cyou
  udp: true
- name: ğŸš©CF | ğŸŸ¢ | vmess | @v2Line | 1
  server: 104.17.148.22
  port: 80
  type: vmess
  uuid: 3e5cda0a-6122-4f54-9e3c-3f49e7a526f9
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: nlch.blueberrynetwork.store
  network: ws
  ws-opts:
    path: /
    headers:
      Host: nlch.blueberrynetwork.store
  udp: true
- name: ğŸ”’ VM-WS-NA ğŸ´â€â˜ ï¸ NA-172.67.201.222:80
  server: 172.67.201.222
  port: 80
  type: vmess
  uuid: b831381d-6324-4d53-ad4f-8cda48b30811
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: 172.67.201.222
  network: ws
  ws-opts:
    path: /graphql
    headers:
      Host: 172.67.201.222
  udp: true
- name: 'ğŸ†” @v2ray_configs_pool '
  server: 104.21.51.208
  port: 80
  type: vmess
  uuid: cb4fca5f-edf8-415b-aa8f-ac52f415296a
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: deefull.tradex2080.com
  network: ws
  ws-opts:
    path: /0fpZFB6IbpNptGAxAtI0QM
    headers:
      Host: deefull.tradex2080.com
  udp: true
- name: 'ğŸ†” @v2ray_configs_pool '
  server: 104.26.15.148
  port: 80
  type: vmess
  uuid: 6965a407-7549-436e-8064-22e3d3d2e7cd
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: 58892877706648357761980405045364.chrsjfklsdjfkljoierfdjklfjlkefeojsdlkfjeoifjsdlkfjweoifjlsdchrs.cyou
  network: ws
  ws-opts:
    path: /V2LINE-TELEGRAM-CHANNEL-VMESS-WS
    headers:
      Host: 58892877706648357761980405045364.chrsjfklsdjfkljoierfdjklfjlkefeojsdlkfjeoifjsdlkfjweoifjlsdchrs.cyou
  udp: true
- name: 'ğŸ†” @v2ray_configs_pool '
  server: 172.67.116.48
  port: 80
  type: vmess
  uuid: 22a13aa2-4854-44cb-e090-ec71ab84b1ff
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: wap.hostmjj.com
  network: ws
  ws-opts:
    path: /
    headers:
      Host: wap.hostmjj.com
  udp: true
- name: 'ğŸ†” @v2ray_configs_pool '
  server: 172.66.213.38
  port: 80
  type: vmess
  uuid: f533e37c-9da5-4955-a218-a7886e5719b6
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: nl88.tradex2080.com
  network: ws
  ws-opts:
    path: /NkXnI0l6LGkotMyATWmx5f6MblN
    headers:
      Host: nl88.tradex2080.com
  udp: true
- name: ğŸRELAY-104.16.67.38-1280
  server: 104.16.67.38
  port: 80
  type: vmess
  uuid: 2a8a10fb-9ca3-367e-a234-cf09f841be4f
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: us3e-mmnnfr9dop0.v2freevpn.com
  network: ws
  ws-opts:
    path: /v118-fccxmxm35
    headers:
      Host: us3e-mmnnfr9dop0.v2freevpn.com
  udp: true
- name: Ø±Ø§ÛŒÚ¯Ø§Ù† | VMESS | @mftizi | USğŸ‡ºğŸ‡¸ | 0ï¸âƒ£3ï¸âƒ£
  server: cfcdn3.sanfencdn9.com
  port: 80
  type: vmess
  uuid: c712c725-149f-414a-a684-1e17d137fe4f
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: agzbjszujp4.yofnhkfc.xyz
  network: ws
  ws-opts:
    path: /video/ibCT6z55
    headers:
      Host: agzbjszujp4.yofnhkfc.xyz
  udp: true
- name: Ø±Ø§ÛŒÚ¯Ø§Ù† | VMESS | @DailyV2RY | USğŸ‡ºğŸ‡¸ | 0ï¸âƒ£1ï¸âƒ£
  server: 104.21.51.208
  port: 80
  type: vmess
  uuid: cb4fca5f-edf8-415b-aa8f-ac52f415296a
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: deefull.tradex2080.com
  network: ws
  ws-opts:
    path: /0fpZFB6IbpNptGAxAtI0QM
    headers:
      Host: deefull.tradex2080.com
  udp: true
- name: Ø±Ø§ÛŒÚ¯Ø§Ù† | VMESS | @DailyV2RY | USğŸ‡ºğŸ‡¸ | 0ï¸âƒ£2ï¸âƒ£
  server: 172.66.213.38
  port: 80
  type: vmess
  uuid: f533e37c-9da5-4955-a218-a7886e5719b6
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: nl88.tradex2080.com
  network: ws
  ws-opts:
    path: /NkXnI0l6LGkotMyATWmx5f6MblN
    headers:
      Host: nl88.tradex2080.com
  udp: true
- name: Ø±Ø§ÛŒÚ¯Ø§Ù† | VMESS | @proxystore11 | DEğŸ‡©ğŸ‡ª | 0ï¸âƒ£1ï¸âƒ£
  server: 185.146.173.92
  port: 80
  type: vmess
  uuid: 8639e52b-a0ce-5d68-b465-b594881feb78
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: De1.vmess.site.
  network: ws
  ws-opts:
    path: /vmess
    headers:
      Host: De1.vmess.site.
  udp: true
- name: Ø±Ø§ÛŒÚ¯Ø§Ù† | VMESS | @yaney_01 | USğŸ‡ºğŸ‡¸ | 0ï¸âƒ£1ï¸âƒ£
  server: 207c13fb-83b6-2021-766b-6c95e56a4a33.bugtik.ltd
  port: 80
  type: vmess
  uuid: 46cfcfe1-e450-459d-a3ab-9406011ab3eb
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: tms.dingtalk.com
  network: ws
  ws-opts:
    path: /
    headers:
      Host: tms.dingtalk.com
  udp: true
- name: Ø±Ø§ÛŒÚ¯Ø§Ù† | VMESS | @yaney_01 | USğŸ‡ºğŸ‡¸ | 0ï¸âƒ£2ï¸âƒ£
  server: 7cc02ab9-3478-1733-ea94-2b45d8e115a0.bugtik.ltd
  port: 80
  type: vmess
  uuid: 46cfcfe1-e450-459d-a3ab-9406011ab3eb
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: tms.dingtalk.com
  network: ws
  ws-opts:
    path: /
    headers:
      Host: tms.dingtalk.com
  udp: true
- name: Ø±Ø§ÛŒÚ¯Ø§Ù† | VMESS | @yaney_01 | USğŸ‡ºğŸ‡¸ | 0ï¸âƒ£3ï¸âƒ£
  server: ef4e4860-008c-3e01-d1f8-bd56dc5b419b.oneplus.pub
  port: 80
  type: vmess
  uuid: 46cfcfe1-e450-459d-a3ab-9406011ab3eb
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: tms.dingtalk.com
  network: ws
  ws-opts:
    path: /
    headers:
      Host: tms.dingtalk.com
  udp: true
- name: Ø±Ø§ÛŒÚ¯Ø§Ù† | VMESS | @yaney_01 | USğŸ‡ºğŸ‡¸ | 0ï¸âƒ£4ï¸âƒ£
  server: ddd47481-0d6f-08b9-7209-b0ddc0c5fa45.oneplus.pub
  port: 80
  type: vmess
  uuid: 46cfcfe1-e450-459d-a3ab-9406011ab3eb
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: tms.dingtalk.com
  network: ws
  ws-opts:
    path: /
    headers:
      Host: tms.dingtalk.com
  udp: true
- name: Ø±Ø§ÛŒÚ¯Ø§Ù† | VMESS | @yaney_01 | USğŸ‡ºğŸ‡¸ | 0ï¸âƒ£5ï¸âƒ£
  server: 172.67.116.48
  port: 80
  type: vmess
  uuid: 22a13aa2-4854-44cb-e090-ec71ab84b1ff
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: wap.hostmjj.com
  network: ws
  ws-opts:
    path: /
    headers:
      Host: wap.hostmjj.com
  udp: true
- name: Ø±Ø§ÛŒÚ¯Ø§Ù† | VMESS | @v2Line | USğŸ‡ºğŸ‡¸ | 0ï¸âƒ£1ï¸âƒ£
  server: 104.26.15.148
  port: 80
  type: vmess
  uuid: 6965a407-7549-436e-8064-22e3d3d2e7cd
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: 58892877706648357761980405045364.chrsjfklsdjfkljoierfdjklfjlkefeojsdlkfjeoifjsdlkfjweoifjlsdchrs.cyou
  network: ws
  ws-opts:
    path: /V2LINE-TELEGRAM-CHANNEL-VMESS-WS
    headers:
      Host: 58892877706648357761980405045364.chrsjfklsdjfkljoierfdjklfjlkefeojsdlkfjeoifjsdlkfjweoifjlsdchrs.cyou
  udp: true
